language: node_js
node_js:
- '0.12'
- '0.10'
deploy:
  provider: npm
  email: igor.zalutsky@gmail.com
  api_key:
    secure: znlrLchN04usNRAILqtCTvJZJH121bZpub7rZebbTwRKXyKP+fWJMd6wztHmARo7drnLwehGOaLEriJ95v7ht9fmyDSkq2/qkhIRpo1jC31ATGp6/NT0BiRAOhiIT3aH4uGV5583nEYgZcBGmyMIa6RxL++IU1p5HnxdFoGXHgpn/mluXrwDmUFZgVwZ6VX69YDYIHk8ukXh3QQI9zKzKmcDx/I+ZtHRD2a0LW0PTAYF1jjgZgnvQXi8oIiW4LRvfEdzdkz89xMQIuNW+ljHpvXjP0OGfaMl0OkNxzkJpt/Q+aHBxhKZg2vyzTGHMN28X93dc6F3tMLBVL7bJdN1qfvzKEQZkJ9LHAbp4GFGApcniJMjj3yzvaPxuXfaxV1lmqp6dhNJQ6MNf8JC4BOxpwf7BCI+x8jF/DkK2X/ZkbeXFqhVCB4nMMPe6snbHX7Hy9ZapLU3Fs96rOjcVCusZTtHDPRdjgQSGYfWXTR4vKf6YIJhavLW9X3VA4Thwfm1L/FeoZVLy/+CfPeXRgJ2KPZMU6lYFDvV5BDitbjFzCK6hD3hBA8H65znWO5bo2SDScX7LrbiVoVFBw1pSi3q5pc3/xvbQaq88HlDkTQvlJrYlq1vcGsm/AVBesoLX3rG2SIEu02NTunnf3Rf+xhJxi+1lRfzm5wqx7f4pLe8PzQ=
  on:
    tags: true
